# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('eater', 'Eater'), ('crab', 'Crab'), ('perry', 'Perry'), ('cider', 'Cider'), ('juicer', 'Juicer'), ('cooker', 'Cooker')], max_length=255)),
                ('fruit', models.CharField(choices=[('apple', 'Apple'), ('pear', 'Pear'), ('gage', 'Gage')], max_length=255)),
                ('harvest', models.CharField(blank=True, max_length=255)),
                ('taste', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
