# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=255)),
                ('fruit', models.CharField(blank=True, max_length=255)),
                ('harvest', models.CharField(blank=True, max_length=255)),
                ('taste', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('fruit', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='fruit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='collection.Type'),
        ),
    ]
