# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20171003_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='fruit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
